# permissions for end users to view cleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-viewer-role
rules:
- apiGroups:
  - actions.cnative.dev
  resources:
  - cleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.cnative.dev
  resources:
  - cleaners/status
  verbs:
  - get
