---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - actions.cnative.dev
  resources:
  - cleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.cnative.dev
  resources:
  - cleaners/finalizers
  verbs:
  - update
- apiGroups:
  - actions.cnative.dev
  resources:
  - cleaners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
  - watch
